[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "build123dfromscratch"
requires-python = ">=3.10"
dependencies = [
    "build123d",
    "ocp-vscode"
]

[tool.setuptools]
py-modules = []

